name: Upload Python Package

on:
    release:
        types: [created]

jobs:
    deploy_linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
            - name: Set up Node.js
              uses: actions/setup-node@v1
              env:
                  RUNNER_TEMP: /tmp
              with:
                  node-version: "14.x"
            - name: Install Python dependencies
              run: |
                  python -m venv venv
                  source venv/bin/activate
                  python -m pip install --upgrade pip wheel setuptools
                  pip install twine mkdocs mkdocs-material
            - name: Generate webpack bundle
              working-directory: ./bcml/assets
              run: |
                  npm install
                  ./node_modules/.bin/webpack --mode production
            - name: Build docs
              run: |
                  source venv/bin/activate
                  mkdocs build -d ./bcml/assets/help
            - uses: actions-rs/toolchain@v1
              name: Install Rust
              with:
                profile: minimal
                toolchain: nightly
                override: true
            - uses: messense/maturin-action@v1
              name: Publish with Maturin
              with:
                maturin-version: latest
                command: publish
                args: --release -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
    deploy_windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
            - name: Set up Node.js
              uses: actions/setup-node@v1
              # env:
              #     RUNNER_TEMP: /tmp
              with:
                  node-version: "14.x"
            - name: Install Python dependencies
              run: |
                  python -m venv venv
                  venv/Scripts/activate.ps1
                  python -m pip install --upgrade pip wheel setuptools
                  pip install twine mkdocs mkdocs-material
            - name: Generate webpack bundle
              working-directory: ./bcml/assets
              run: |
                  npm install
                  ./node_modules/.bin/webpack --mode production
            - name: Build docs
              run: |
                  venv/Scripts/activate.ps1
                  mkdocs build -d ./bcml/assets/help
            - uses: actions-rs/toolchain@v1
              name: Install Rust
              with:
                profile: minimal
                toolchain: nightly
                override: true
            - name: Install CMake
              uses: Symbitic/install-cmake@v0.1.0
            - uses: messense/maturin-action@v1
              name: Publish with Maturin
              with:
                maturin-version: latest
                command: publish
                args: --release -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
